version: '2'
services:
    jhipstertraducere-app:
        image: jhipstertraducere
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://jhipstertraducere-postgresql:5432/jhipsterTraducere
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    jhipstertraducere-postgresql:
        extends:
            file: postgresql.yml
            service: jhipstertraducere-postgresql
