version: '2'
services:
    jhipstertraducere-postgresql:
        image: postgres:9.5.4
        # volumes:
        #     - ~/volumes/jhipster/jhipsterTraducere/postgresql/:/var/lib/postgresql/
        environment:
            - POSTGRES_USER=jhipsterTraducere
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
